### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by DonnieTD** [anthonyjoeseph/fp-ts-routing-examples#6]
Thank you for this series !

**Comment by anthonyjoeseph** [comment]
Sure thing!! May I ask how you found out about it?

**Comment by DonnieTD** [comment]
I have been studying category theory and been looking for ways to use that
kind of thinking in my work

Found fp-ts

Looked for other fp ts projects

Found your router

Saw the tagline said video series

Searched for it on YouTube and found it xD

And tbh it brought me a lot of value for the amount of time it took me to
watch and read through the source

**Comment by anthonyjoeseph** [comment]
I'm so glad you found it, thank you for your kind words and good luck on your category theory journey!
